### ISSUE TITLE
Define for 2-keys keyboard for loop FIELD value

### ISSUE THREAD

**Issue by dontsovcmc** [neu-rah/ArduinoMenu#58]
I you have only 2 keys in your device you can't change values in FIELDs cause you can't go down after maximum value. So, we can change clamp() function with ONLY_UP_KEY definition.

```
void clamp() {
      if (value<low) value=low;
#ifdef ONLY_UP_KEY
      else if (value>high) value=low;
#else
      else if (value>high) value=high;
#endif
}
```

**Comment by neu-rah** [comment]
true indeed

can you open a pull request with this changes and also with the debounce safe code?
This way you keep the authoring, otherwise it would be as if it was all my code.

Note for myself: use wrapStyle on version 3 to control this.

**Comment by dontsovcmc** [comment]
Wait a minute please, I try to understand how to do it correctly. 
https://guides.github.com/activities/contributing-to-open-source/

**Comment by dontsovcmc** [comment]
done )

**Comment by neu-rah** [comment]
https://github.com/neu-rah/ArduinoMenu/pull/59

**Comment by dontsovcmc** [comment]
It's better to do loop in menu items also... I try to find place in your code and make pull request.

**Comment by neu-rah** [comment]
worry not , version 3 already has it, its on dev branch

**Comment by neu-rah** [comment]
syntax is a bit different, but you might guess from the examples (still have to write the docs :\ ) and still missing things like UTFT/UTouch support.
on v3 wrap is done at item level instead of global
